name: No Duplications

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: No Duplication beyond 3 lines
      run: jscpd --ignore "./bms_receiver/bms_receiver_test.py" . --min-lines 3 --min-tokens 48 --threshold 0
